apiVersion: v1
kind: ClusterRole
metadata:
  annotations:
    authorization.openshift.io/system-only: "true"
  name: hawkular-metrics-admin
rules:
- apiGroups:
  - ""
  resources:
  - hawkular-metrics
  - hawkular-alerts
  verbs:
  - '*'
