id: hawkular-heapster
kind: Template
apiVersion: v1
name: Hawkular Heapster Template
description: Configures a Heapster template to be used with Hawkular Metrics.
metadata:
  name: hawkular-heapster
  labels:
    metrics-infra: heapster
parameters:
- description: Internal URL for the master, for authentication retrieval
  name: MASTER_URL
  value: https://kubernetes.default.svc:443
- description: Specify prefix for metrics components; e.g. for "openshift/origin-metrics-deployer:v1.1",
    set prefix "openshift/origin-"
  name: IMAGE_PREFIX
  value: openshift/origin-
- description: Specify version for metrics components; e.g. for "openshift/origin-metrics-deployer:v1.1",
    set version "v1.1"
  name: IMAGE_VERSION
  value: latest
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: heapster
    labels:
      metrics-infra: support
  secrets:
  - name: heapster-secrets
  - name: hawkular-metrics-certificate
  - name: hawkular-metrics-account
- apiVersion: v1
  kind: Service
  metadata:
    name: heapster
    labels:
      metrics-infra: heapster
      name: heapster
  spec:
    selector:
      name: heapster
    ports:
    - port: 80
      targetPort: http-endpoint
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: heapster
    labels:
      metrics-infra: heapster
      name: heapster
  spec:
    selector:
      name: heapster
    replicas: 1
    template:
      version: v1
      metadata:
        labels:
          metrics-infra: heapster
          name: heapster
      spec:
        containers:
        - image: "${IMAGE_PREFIX}metrics-heapster:${IMAGE_VERSION}"
          name: heapster
          ports:
          - name: http-endpoint
            containerPort: 8082
          command:
          - "heapster-wrapper.sh"
          - "--wrapper.username_file=/hawkular-account/hawkular-metrics.username"
          - "--wrapper.password_file=/hawkular-account/hawkular-metrics.password"
          - "--wrapper.allowed_users_file=/secrets/heapster.allowed-users"
          - "--wrapper.endpoint_check=https://hawkular-metrics:443/hawkular/metrics/status"
          - "--source=kubernetes:${MASTER_URL}?useServiceAccount=true&kubeletHttps=true&kubeletPort=10250"
          - "--sink=hawkular:https://hawkular-metrics:443?tenant=_system&labelToTenant=pod_namespace&caCert=/hawkular-cert/hawkular-metrics-ca.certificate&user=%username%&pass=%password%&filter=label(container_name:^/system.slice.*|^/user.slice)"
          - "--tls_cert=/secrets/heapster.cert"
          - "--tls_key=/secrets/heapster.key"
          - "--tls_client_ca=/secrets/heapster.client-ca"
          - "--allowed_users=%allowed_users%"
          volumeMounts:
          - name: heapster-secrets
            mountPath: "/secrets"
          - name: hawkular-metrics-certificate
            mountPath: "/hawkular-cert"
          - name: hawkular-metrics-account
            mountPath: "/hawkular-account"
          readinessProbe:
            exec:
              command:
              - "/opt/heapster-readiness.sh"
        volumes:
        - name: heapster-secrets
          secret:
            secretName: heapster-secrets
        - name: hawkular-metrics-certificate
          secret:
            secretName: hawkular-metrics-certificate
        - name: hawkular-metrics-account
          secret:
            secretName: hawkular-metrics-account
        serviceAccount: heapster
