id: hawkular-support
kind: Template
apiVersion: v1
name: Hawkular Support Template
description: Template for setting up various support components for Hawkular Metrics.
metadata:
  name: hawkular-support
  labels:
    metrics-infra: support
parameters:
- description: ''
  name: HAWKULAR_METRICS_HOSTNAME
  required: true
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: hawkular
    labels:
      metrics-infra: support
  secrets:
  - name: hawkular-metrics-secrets
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: cassandra
    labels:
      metrics-infra: support
  secrets:
  - name: hawkular-cassandra-secrets
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: heapster
    labels:
      metrics-infra: support
  secrets:
  - name: heapster-secrets
  - name: hawkular-metrics-certificate
  - name: hawkular-metrics-account
- apiVersion: v1
  kind: Route
  metadata:
    name: hawkular-metrics
    labels:
      metrics-infra: support
  spec:
    host: "${HAWKULAR_METRICS_HOSTNAME}"
    to:
      kind: Service
      name: hawkular-metrics
    tls:
      termination: passthrough
