id: hawkular-support
kind: Template
apiVersion: v1
name: Hawkular Support Template
description: Template for setting up various support components for Hawkular Metrics.
metadata:
  name: hawkular-support
  labels:
    metrics-infra: support
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: hawkular
    labels:
      metrics-infra: support
  secrets:
  - name: hawkular-metrics-secrets
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: cassandra
    labels:
      metrics-infra: support
  secrets:
  - name: hawkular-cassandra-secrets
