#!/bin/bash
#
# Copyright 2014-2015 Red Hat, Inc. and/or its affiliates
# and other contributors as indicated by the @author tags.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

for args in "$@"
do
  case $args in
    --seeds=*)
      SEEDS="${args#*=}"
    ;;
    --cluster_name=*)
      CLUSTER_NAME="${args#*=}"
    ;;
    --data_volume=*)
      DATA_VOLUME="${args#*=}"
    ;;
    --commitlog_volume=*)
      COMMITLOG_VOLUME="${args#*=}"
    ;;
    --seed_provider_classname=*)
      SEED_PROVIDER_CLASSNAME="${args#*=}"
    ;;
    --keystore-dir=*)
      KEYSTORE_DIR="${args#*=}"
    ;;
    --keystore-file=*)
      KEYSTORE_FILE="${args#*=}"
    ;;
    --keystore-password=*)
      KEYSTORE_PASSWORD="${args#*=}"
    ;;
    --truststore-file=*)
      TRUSTSTORE_FILE="${args#*=}"
    ;;
    --truststore-password=*)
      TRUSTSTORE_PASSWORD="${args#*=}"
    ;;
    --service-cert=*)
      SERVICE_CERT="${args#*=}"
    ;;
    --service-cert-key=*)
      SERVICE_CERT_KEY="${args#*=}"
    ;;
    --service-ca=*)
      SERVICE_CA="${args#*=}"
    ;;
    --help)
      HELP=true
    ;;
  esac
done

if [ -n "$HELP" ]; then
  echo
  echo Starts up a Cassandra Docker image
  echo
  echo Usage: [OPTIONS]...
  echo
  echo Options:
  echo "  --seeds=SEEDS"
  echo "        comma separated list of hosts to use as a seed list"
  echo "        default: \$HOSTNAME"
  echo
  echo "  --cluster_name=NAME"
  echo "        the name to use for the cluster"
  echo "        default: test_cluster"
  echo
  echo "  --data_volume=VOLUME_PATH"
  echo "        the path to where the data volume should be located"
  echo "        default: \$CASSANDRA_HOME/data"
  echo
  echo "  --seed_provider_classname"
  echo "        the classname to use as the seed provider"
  echo "        default: org.apache.cassandra.locator.SimpleSeedProvider"
  echo
  echo "  --keystore-dir"
  echo "        the location for the keystore and trust store files"
  echo "        default: CASSANDRA_HOME/conf"
  echo
  echo "  --keystore-file"
  echo "        the path to the keystore file"
  echo "        default: CASSANDRA_HOME/conf/.keystore"
  echo
  echo "  --keystore-password"
  echo "        the keystore password"
  echo "        default: a random string"
  echo
  echo "  --truststore-file"
  echo "        the path to the trust store file"
  echo "        default: CASSANDRA_HOME/conf/.truststore"
  echo
  echo "  --truststore-password"
  echo "        the truststore password"
  echo "        default: a random string"
  echo
  echo "  --service-cert"
  echo "        the cert for this service"
  echo "        default: the tls.crt generated by OpenShift and mounted as secret"
  echo
  echo "  --service-cert-key"
  echo "        the cert key for this service"
  echo "        default: the tls.key generated by OpenShift and mounted as secret"
  echo
  echo "  --service-ca"
  echo "        the CA file to include into the trust store"
  echo "        default: the same as the service-cert"

  echo
  exit 0
fi

CASSANDRA_HOME=${CASSANDRA_HOME:-"/opt/apache-cassandra"}
CASSANDRA_CONF=${CASSANDRA_CONF:-"${CASSANDRA_HOME}/conf"}
CASSANDRA_CONF_FILE=${CASSANDRA_CONF_FILE:-"${CASSANDRA_CONF}/cassandra.yaml"}
KEYSTORE_DIR=${KEYSTORE_DIR:-"${CASSANDRA_CONF}"}

KEYSTORE_FILE=${KEYSTORE_FILE:-"${KEYSTORE_DIR}/.keystore"}
KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD:-$(head /dev/urandom -c 512 | tr -dc A-Z-a-z-0-9 | head -c 17)}

TRUSTSTORE_NODES_FILE=${TRUSTSTORE_NODES_FILE:-"${KEYSTORE_DIR}/.nodes.truststore"}
TRUSTSTORE_NODES_PASSWORD=${TRUSTSTORE_NODES_PASSWORD:-$(head /dev/urandom -c 512 | tr -dc A-Z-a-z-0-9 | head -c 17)}

TRUSTSTORE_CLIENTS_FILE=${TRUSTSTORE_CLIENTS_FILE:-"${KEYSTORE_DIR}/.clients.truststore"}
TRUSTSTORE_CLIENTS_PASSWORD=${TRUSTSTORE_CLIENTS_PASSWORD:-$(head /dev/urandom -c 512 | tr -dc A-Z-a-z-0-9 | head -c 17)}

SERVICE_ALIAS=${SERVICE_ALIAS:-"cassandra"}
SERVICE_CERT=${SERVICE_CERT:-"/secrets/tls.crt"}
SERVICE_CERT_KEY=${SERVICE_CERT_KEY:-"/secrets/tls.key"}

SERVICE_CA=${SERVICE_CA:-"${CASSANDRA_CONF}/cas-to-import01"}
SERVICE_CA_ORIGINAL=${SERVICE_CA_ORIGINAL:-"/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"}
SERVICE_CA_ALIAS=${SERVICE_CA_ALIAS:-"services-ca"}

PKCS12_FILE=${PKCS12_FILE:-"${KEYSTORE_DIR}/cassandra.pkcs12"}
KEYTOOL_COMMAND="/usr/lib/jvm/java-1.8.0/jre/bin/keytool"

## some extra cassandra.yaml options
## those options can be overridden, but shouldn't be changed without tweaking the
## options above
INTERNODE_ENCRYPTION=${INTERNODE_ENCRYPTION:-"all"}
ENABLE_CLIENT_ENCRYPTION=${ENABLE_CLIENT_ENCRYPTION:-"true"}

## the certs provided by OpenShift have a flag explicitly forbidding it from being used as client certs
## so, we default to false, but allow users to override, should a SERVICE_CERT be provided that can be used
## as client cert as well as server cert
REQUIRE_NODE_AUTH=${REQUIRE_NODE_AUTH:-"false"}
REQUIRE_CLIENT_AUTH=${REQUIRE_CLIENT_AUTH:-"false"}

## set up the keystore, where our own keys are kept
echo "Creating the Cassandra keystore from the Secret's cert data"
openssl pkcs12 -export -in ${SERVICE_CERT} -inkey ${SERVICE_CERT_KEY} -out ${PKCS12_FILE} -name ${SERVICE_ALIAS} -noiter -nomaciter -password pass:${KEYSTORE_PASSWORD}
if [ $? != 0 ]; then
    echo "Failed to create a PKCS12 certificate file with the service-specific certificate. Aborting."
    exit 1
fi
echo "Converting the PKCS12 keystore into a Java Keystore"
${KEYTOOL_COMMAND} -v -importkeystore -srckeystore ${PKCS12_FILE} -srcstoretype PKCS12 -destkeystore ${KEYSTORE_FILE} -deststoretype JKS -deststorepass ${KEYSTORE_PASSWORD} -srcstorepass ${KEYSTORE_PASSWORD}
if [ $? != 0 ]; then
    echo "Failed to create a Java Keystore file with the service-specific certificate. Aborting."
    exit 1
fi

# the next few lines deserve an explanation: the service-ca.crt provided by OpenShift contains the root CA and the
# service-ca certificates in a single file. Java's keytool can't handle this, it seems, and ends up importing only
# the first one. So, we split the file, having one cert per resulting file. The next lines are for that, and
# will only work properly on the scenario described. If the scenario ever changes, the next lines will probably
# need to be adapted accordingly. The best solution would be to have one cert per file.
PREV_DIR=${PWD}
cd ${CASSANDRA_CONF}
csplit -z -f cas-to-import ${SERVICE_CA_ORIGINAL} '/-----BEGIN CERTIFICATE-----/' '{*}' > /dev/null
cd ${PREV_DIR}

## set up the trust store for the inter node communication
## we trust only our own cert
echo "Building the trust store for inter node communication"
${KEYTOOL_COMMAND} -noprompt -import -alias ${SERVICE_ALIAS} -file ${SERVICE_CERT} -keystore ${TRUSTSTORE_NODES_FILE} -trustcacerts -storepass ${TRUSTSTORE_NODES_PASSWORD}
if [ $? != 0 ]; then
    echo "Failed to build the trust store by importing the service CA. Aborting."
    exit 1
fi

## set up the trust store for the client communication
## we trust all certs issued by the service-ca
echo "Building the trust store for client communication"
${KEYTOOL_COMMAND} -noprompt -import -alias ${SERVICE_CA_ALIAS} -file ${SERVICE_CA} -keystore ${TRUSTSTORE_CLIENTS_FILE} -trustcacerts -storepass ${TRUSTSTORE_CLIENTS_PASSWORD}
if [ $? != 0 ]; then
    echo "Failed to import the Service CA cert for client communication. Aborting."
    exit 1
fi

if [ -z "${MAX_HEAP_SIZE}" ]; then
  if [ -z "${MEMORY_LIMIT}" ]; then
    MEMORY_LIMIT=`cat /sys/fs/cgroup/memory/memory.limit_in_bytes`
    echo "The MEMORY_LIMIT envar was not set. Reading value from /sys/fs/cgroup/memory/memory.limit_in_bytes."
  fi
  echo "The MAX_HEAP_SIZE envar is not set. Basing the MAX_HEAP_SIZE on the available memory limit for the pod (${MEMORY_LIMIT})."
  BYTES_MEGABYTE=1048576
  BYTES_GIGABYTE=1073741824
  # Based on the Cassandra memory limit recommendations. See http://docs.datastax.com/en/cassandra/2.2/cassandra/operations/opsTuneJVM.html
  if (( ${MEMORY_LIMIT} <= (2 * ${BYTES_GIGABYTE}) )); then
    # If less than 2GB, set the heap to be 1/2 of available ram
    echo "The memory limit is less than 2GB. Using 1/2 of available memory for the max_heap_size."
    export MAX_HEAP_SIZE="$((${MEMORY_LIMIT} / ${BYTES_MEGABYTE} / 2 ))M"
  elif (( ${MEMORY_LIMIT} <= (4 * ${BYTES_GIGABYTE}) )); then
    echo "The memory limit is between 2 and 4GB. Setting max_heap_size to 1GB."
    # If between 2 and 4GB, set the heap to 1GB
    export MAX_HEAP_SIZE="1024M"
  elif (( ${MEMORY_LIMIT} <= (32 * ${BYTES_GIGABYTE}) )); then
    echo "The memory limit is between 4 and 32GB. Using 1/4 of the available memory for the max_heap_size."
    # If between 4 and 32GB, use 1/4 of the available ram
    export MAX_HEAP_SIZE="$(( ${MEMORY_LIMIT} / ${BYTES_MEGABYTE} / 4 ))M"
  else
    echo "The memory limit is above 32GB. Using 8GB for the max_heap_size"
    # If above 32GB, set the heap size to 8GB
    export MAX_HEAP_SIZE="8192M"
  fi
  echo "The MAX_HEAP_SIZE has been set to ${MAX_HEAP_SIZE}"
else
  echo "The MAX_HEAP_SIZE envar is set to ${MAX_HEAP_SIZE}. Using this value"
fi

if [ -z "${HEAP_NEWSIZE}" ] && [ -z "${CPU_LIMIT}" ]; then
  echo "The HEAP_NEWSIZE and CPU_LIMIT envars are not set. Defaulting the HEAP_NEWSIZE to 100M"
  export HEAP_NEWSIZE=100M
elif [ -z "${HEAP_NEWSIZE}" ]; then
  export HEAP_NEWSIZE=$((CPU_LIMIT/10))M
  echo "THE HEAP_NEWSIZE envar is not set. Setting to ${HEAP_NEWSIZE} based on the CPU_LIMIT of ${CPU_LIMIT}. [100M per CPU core]"
else
  echo "The HEAP_NEWSIZE envar is set to ${HEAP_NEWSIZE}. Using this value"
fi

#Update the cassandra-env.sh with these new values
cp ${CASSANDRA_CONF}/cassandra-env.sh.template ${CASSANDRA_CONF}/cassandra-env.sh
sed -i 's/${MAX_HEAP_SIZE}/'$MAX_HEAP_SIZE'/g' ${CASSANDRA_CONF}/cassandra-env.sh
sed -i 's/${HEAP_NEWSIZE}/'$HEAP_NEWSIZE'/g' ${CASSANDRA_CONF}/cassandra-env.sh

cp ${CASSANDRA_CONF_FILE}.template ${CASSANDRA_CONF_FILE}

# set the hostname in the cassandra configuration file
sed -i 's/${HOSTNAME}/'$HOSTNAME'/g' ${CASSANDRA_CONF_FILE}

# if the seed list is not set, try and get it from the gather-seeds script
if [ -z "$SEEDS" ]; then
  source ${CASSANDRA_HOME}/bin/gather-seeds.sh
fi

echo "Setting seeds to be ${SEEDS}"
sed -i 's/${SEEDS}/'$SEEDS'/g' ${CASSANDRA_CONF_FILE}

# set the cluster name if set, default to "test_cluster" if not set
if [ -n "$CLUSTER_NAME" ]; then
    sed -i 's/${CLUSTER_NAME}/'$CLUSTER_NAME'/g' ${CASSANDRA_CONF_FILE}
else
    sed -i 's/${CLUSTER_NAME}/test_cluster/g' ${CASSANDRA_CONF_FILE}
fi

# set the data volume if set, otherwise use the CASSANDRA_HOME location, otherwise default to '/cassandra_data'
if [ -n "$DATA_VOLUME" ]; then
    sed -i 's#${DATA_VOLUME}#'$DATA_VOLUME'#g' ${CASSANDRA_CONF_FILE}
elif [ -n "$CASSANDRA_HOME" ]; then
    DATA_VOLUME="$CASSANDRA_HOME/data"
    sed -i 's#${DATA_VOLUME}#'$CASSANDRA_HOME'/data#g' ${CASSANDRA_CONF_FILE}
else
    DATA_VOLUME="/cassandra_data"
    sed -i 's#${DATA_VOLUME}#/cassandra_data#g' ${CASSANDRA_CONF_FILE}
fi

# set the commitlog volume if set, otherwise use the DATA_VOLUME value instead
if [ -n "$COMMITLOG_VOLUME" ]; then
  sed -i 's#${COMMITLOG_VOLUME}#'$COMMITLOG_VOLUME'#g' ${CASSANDRA_CONF_FILE}
else
  sed -i 's#${COMMITLOG_VOLUME}#'$DATA_VOLUME'#g' ${CASSANDRA_CONF_FILE}
fi

# set the seed provider class name, otherwise default to the SimpleSeedProvider
if [ -n "$SEED_PROVIDER_CLASSNAME" ]; then
    sed -i 's#${SEED_PROVIDER_CLASSNAME}#'$SEED_PROVIDER_CLASSNAME'#g' ${CASSANDRA_CONF_FILE}
else
    sed -i 's#${SEED_PROVIDER_CLASSNAME}#org.apache.cassandra.locator.SimpleSeedProvider#g' ${CASSANDRA_CONF_FILE}
fi

sed -i 's#${KEYSTORE_FILE}#'${KEYSTORE_FILE}'#g' ${CASSANDRA_CONF_FILE}
sed -i 's#${KEYSTORE_PASSWORD}#'${KEYSTORE_PASSWORD}'#g' ${CASSANDRA_CONF_FILE}
sed -i 's#${TRUSTSTORE_NODES_FILE}#'${TRUSTSTORE_NODES_FILE}'#g' ${CASSANDRA_CONF_FILE}
sed -i 's#${TRUSTSTORE_NODES_PASSWORD}#'${TRUSTSTORE_NODES_PASSWORD}'#g' ${CASSANDRA_CONF_FILE}
sed -i 's#${TRUSTSTORE_CLIENTS_FILE}#'${TRUSTSTORE_CLIENTS_FILE}'#g' ${CASSANDRA_CONF_FILE}
sed -i 's#${TRUSTSTORE_CLIENTS_PASSWORD}#'${TRUSTSTORE_CLIENTS_PASSWORD}'#g' ${CASSANDRA_CONF_FILE}
sed -i 's#${INTERNODE_ENCRYPTION}#'${INTERNODE_ENCRYPTION}'#g' ${CASSANDRA_CONF_FILE}
sed -i 's#${ENABLE_CLIENT_ENCRYPTION}#'${ENABLE_CLIENT_ENCRYPTION}'#g' ${CASSANDRA_CONF_FILE}
sed -i 's#${REQUIRE_NODE_AUTH}#'${REQUIRE_NODE_AUTH}'#g' ${CASSANDRA_CONF_FILE}
sed -i 's#${REQUIRE_CLIENT_AUTH}#'${REQUIRE_CLIENT_AUTH}'#g' ${CASSANDRA_CONF_FILE}

# create the cqlshrc file so that cqlsh can be used much more easily from the system
mkdir -p $HOME/.cassandra
cat >> $HOME/.cassandra/cqlshrc << DONE
[connection]
hostname= $HOSTNAME
port = 9042

[ssl]
certfile = ${SERVICE_CERT}
DONE

# verify that we are not trying to run an older version of Cassandra which has been configured for a newer version.
if [ -f ${CASSANDRA_DATA_VOLUME}/.cassandra.version ]; then
    previousVersion=$(cat ${CASSANDRA_DATA_VOLUME}/.cassandra.version)
    echo "The previous version of Cassandra was $previousVersion. The current version is $CASSANDRA_VERSION"
    previousMajor=$(cut -d "." -f 1 <<< "$previousVersion")
    previousMinor=$(cut -d "." -f 2 <<< "$previousVersion")

    currentMajor=$(cut -d "." -f 1 <<< "$CASSANDRA_VERSION")
    currentMinor=$(cut -d "." -f 2 <<< "$CASSANDRA_VERSION")

    if (( ($currentMajor < $previousMajor) || (($currentMajor == $previousMajor) && ($currentMinor < $previousMinor)) )); then
       echo "Error: the data volume associated with this pod is configured to be used with Cassandra version $previousVersion"
       echo "       or higher. This pod is using Cassandra version $CASSANDRA_VERSION which does not meet this requirement."
       echo "       This pod will not be started."
       exit 1
    fi
fi

# remove -R once CASSANDRA-12641 is fixed
exec ${CASSANDRA_HOME}/bin/cassandra -f -R